### ISSUE TITLE
Aggiunte alle api

### ISSUE THREAD

**Issue by LucaCarrero** [AugMantua/ScienceGround2021#9]
- [X] utilizzare e valorizzare la tabella con le info di un sensore (#10)
- [X] aggiungere la tabella che connette un terrario alle informazioni dei sensori (#10)
- [X] nella get dei terrari per ognuno ritornare la lista dei sensori presenti con le informazioni su ogni sensore ( prendendole dalla tabella che contiene le informazioni sui sensori) (#10)
